export const samstöðusjónarmiðið = {
  pointTitil: 'Samstöðusjónarmiðið',
  pointText: 'Samstöðusjónarmiðið í afbrotafræði hefur rætur sínar í samvirkni skólanum í félagsfræði. Í þessu sjónarmiði er áhersla lögð á sameiningu ýmissa hópa í samfélaginu til að uppfylla heildar þarfir samfélagsins. Samstöðusjónarmiðið skoðar afbrot í ljósi refsilaga, sem gegna þremur grundvallar hlutverkum að tilgreina refsivert atferli, koma í veg fyrir tjón sem af afbrotum hlýst og skýra viðurlög við brot.',
  pointText1: 'Afbrotafræðin skiptist í tvo megin skóla sem eru klassíska skólann og pósitífska skólann. Klassíski skólinn sem hefur starfað síðan 18. öld leggur áherslu á frjálsan vilja einstaklings til að velja milli laga og glæp. Hræðsla við refsingu er talin fæla einstaklinga frá glæpi og áhrif samfélagsins á afbrot eru litið á sem mestum verðmætum. Þessi skóli leggur áherslu á að réttarkerfið sé skilvirkara í að fyrirbyggja brot með að gera refsilögin hættulegri en ánægjulegri.',
  pointText2: 'Pósitífska skólann segir frá því að hegðun einstaklinga sé ráðin af margvíslegum þáttum þar sem þeir hafa takmarkaða stjórn á ákvarðanatökum sínum. Afbrot eru leidd út frá líffræðilegum skýringum og hegðun einstaklinga er háð ótal þáttum þar á meðal sálfræðilegum og umhverfisþáttum, sem einstaklingurinn hefur oft litla stjórn á. Þessi sjónarmið leggja áherslu á samspil ákvarðanatökum einstaklingsins og áreiti úr umhverfinu þar sem báðir þættir móta atferlið.',
  pointText3: 'Afbrotamenn og venjulegir borgarar eru í grundvallaratriðum ólíkir vegna mismunandi líffræðilegra eða sálfræðilegra þátta sem móta þeirra atferli. Þar sem áhrif þessara þátta eru fjölbreytt er mikilvægt að skoða þá sem áhrifaþætti þar á meðal erfðir greind og persónuleiki. Þessir þættir mynda grunninn sem einkennir einstaklinginn og geta haft áhrif á hvernig hann svarar áreitum í umhverfinu, hvort hann reyndist með samfélaginu eða stefni að afbrotum. Þannig gagnast þessi sjónarmið við að skilja fjölbreytt atferli einstaklinga og rannsaka þá þætti sem hafa áhrif á valkosti þeirra.',
}
export const samskiptasjónarmiðið = {
  pointTitil: 'Samskiptasjónarmiðið',
  pointText: 'Samskiptasjónarmiðið í afbrotafræði er skipt í tvennt: félagsnám og stimplun. Félagsnám kenningarinnar miðar að því að einstaklingar læri afbrotahegðun í nánum samskiptum við jafningjahópinn, en stimplun skoðar á áhrif þess hvernig einstaklingar og hópar skilgreina og merkja afbrot.',
  pointText1: 'Félagsnám byggir á þeirri hugmynd að afbrotamenn hafi kynnt sér ýmsar aðferðir og hugmyndir um afbrot í samskiptum, en einnig tileinki sér réttlætingu og afneitun afbrota. Sykes og Matza rísa fram með fimm aðferðir sem brotamenn nota til að réttlæta afbrot sín: afneitun ábyrgðar, afneitun skaða, afneitun fórnarlambs, fordæming á þeim sem fordæma, og hollusta við félagana. Þeir leggja áherslu á að afbrotamenn þekki samfélagsgildi en noti þó hvernig sem er aðferðir til að undanþiggja eigin ábyrgð á afbrotinu.',
  pointText2: 'Stimplunarsjónarmiðið birtist sem önnur helming af samskipta sjónarmiðinu og telur að afbrot séu eingöngu afbrot ef þau eru skilgreind af samfélaginu eða einstaklingum sem frávik eða afbrot. Því hefur afbrot enga merkingu nema þau verði stimpluð af umhverfinu. Edwin Lemert er talinn forgrunnsmaður stimplunarkenninga og lýsir því hvernig einstaklingurinn getur breytt sjálfum sér, beroande á því hvernig hann er skilgreindur af samfélaginu. Stimplunarsjónarmiðið leggur áherslu á að fyrstu viðbrögð samfélagsins við einstaklingum sem fram fara afbrotum geti verið áhrifarík og haft áhrif á sjálfsvirðingu og áframhaldandi hegðun þeirra.',
  pointText3: 'Þessar kenningar draga fram mikilvægi samskipta og áhrifa umhverfisins í skilningi á afbrotum. Þær reyna að skoða rætur afbrotamanna, séu þær í nánum samskiptum eða skilgreiningu á frávikinu. Með því að leggja áherslu á hvernig einstaklingar sem skiptast við samfélagið sitt og hvernig afbrotin eru túlkuð af umhverfinu, eiga þessar kenningar að hjálpa við að fá betra innsýn og skilja hvernig og af hverju afbrot verða.',
}
export const átakasjónarmiðið = {
  pointTitil: 'Átakasjónarmiðið',
  pointText: 'Átakasjónarmiðið í afbrotafræði leggur áherslu á átök og takmörkuð gæði í samfélaginu sem uppspretta afbrota. Þetta sjónarmið er í grundvallaratriðum róttækari útgáfa af stimplunar sjónarmiðinu og var algengt á 70. og 80. áratugum. Það byggir á hugmyndinni að samfélagið séu myndað af ýmsum hópum með mismunandi hagsmuni, sem berjast um takmörkuð auðlindir. Þessir hópar geta verið mismunandi eftir kynþætti, menningarhópa, stéttum eða efnahagsstöðu, og átök þeirra geta verið opinber eða dulin, en þau eru stöðugt til staðar.',
  pointText1: 'Fylgjendur átakasjónarmið sins greina oft tvo mismunandi hópa. Annar hópurinn, sem má rekja til Sellin og Vold og Bernard, túlkar átök og afbrot sem fylgikvilla í flókin samfélög, þar sem mismunandi kynþættir og menningarhópar búa saman. Þessir átakasjónarmenn telja að ágreiningur um löggjafann upp komist fyrst og fremst vegna menningarmála. Þeir lýsa átökum sem eiga upphaf sín í árekstri milli hópa, svo sem þegar áfengisbannið í Bandaríkjunum á 20. öld er skýrt út frá baráttu milli dreifbýlis og þéttbýlis, mótmælenda og katólika.',
  pointText2: 'Hins vegar túlkar annar hópur átakasjónarmanna, sem átakast fyrir stéttaátökum, afbrot framar stéttaárekstri. Þeir, eins og Taylor, Walton, Young og Quinney, lýsa afbrotum í ljósi stéttaátaka, og segja að erfitt sé að komast hjá því að refsilögin hneigist til að draga úr taumum þeirra sem hafa vald og fjármagn, á kostnað þeirra sem standa í lélegri stöðu. Þeir bendi á að refsilögin séu hæfilega hagsmunaátæk og hægt sé að rekja hærri refsingar við strætisglæpi til hagsmuna yfirmagna, og að skilgreining af brotaflokkum geti verið óljósari og ónákvæmari þegar kemur að hegðun betur settra hópa.',
  pointText3: 'Að taka sjónarmiðinu fylgja spurningar um hagsmuni sem laganna framkvæmdir og skilgreiningar á afbrotum gætu gagnast. Hvernig er refsilögum beitt, og hver eru hagsmunir þeirra sem hafa sterkari stöðu? Er hagsmunum einhverra hópa beitt fyrir borð, og hvernig er átakasjónarmiðið varpa ljósi á atferli og lögbrot yfirvalda og auðmagn? Þessar spurningar veita innsýn og skilja betur hvernig samfélagið og réttarkerfið haga sér í árekstrinum milli hagsmuna mismunandi hópa.',
}

export const fíkniefnaneysla = {
  skoðanirTitil: 'Okkar skoðanir',
  skoðanirText: 'Afbrot eru á hverjum degi en það eru sum frægari en önnur og eru með meiri tíðni. Við teljum að eftir tíu ár mun fíkniefni vera stórt mál því fólk er háð því og getur ekki lifað án fíkniefnis. Fólk er alltaf að selja og kaupa fíkniefni munu alltaf vera stór partur af samfélaginu.',
  
  samstöðuTitil: 'Samstöðusjónarmiðinu',
  samstöðuText: 'Samkvæmt samstöðusjónarmiðinu eru tvær leiðir að skoða afhverju manneskja notar fíkniefni. Klassíski skólinn segir að manneskja notar fíkniefni vegna þess að hún ræður yfir sjálfum sér og ákveður sjálf hvort hún fylgir lögum og reglum. Pósitífíski skólinn segir að manneskja notar fíkniefni vegna þess að hún er ekki góð eða slæm heldur er hún með líffræðileg gen sem láta hana gera hlutina sem hún gerir. Til þess að koma í veg fyrir notkun á fíkniefnum samkvæmt klassíska skólanum er sagt að herða lögin fyrir afbrotinu. Pósitífíski skólinn segir að finna af hverju manneskjur nota fíkniefni og reyna að hjálpa manneksjunni að hætta að nota Fíkniefni. Það er hugsað að láta manneskju fara í meðferð og takast á við vandamálin sín.',
  
  samskiptaTitil: 'Samskiptasjónarmiðið',
  samskiptaText: 'Samskiptasjónarmiðið segir að manneskja lærir að nota fíkniefni frá öðru fólki í jafningjahópi. Kenning um áherslu um stimplun segir að það er ekki ólöglegt að að nota og selja fíkniefni nema hópur eða einstaklingur segir að þetta er ólöglegt. Kenningar með áherslu á félagsnám segir að til þess að draga úr útbreiðslu á fíkniefnum ætti að minnka hugmyndir um fíkniefni og ekki leyfa fólki að heyra og sjá fíkniefni. Kenningar með áherslu á stimplun segir til að draga út úr útbreiðslu á fíkniefnum ætti fólk að passa sig hvernig það kemur fram við fólk sem er stimplað sem afbrota manneskja svo það fer ekki að gera fleiri afbrot.',

  átakaTitil: 'Átakasjónarmiðið',
  átakaText: 'Átakasjónarmiðið segir að refsilög fyrir fíkniefni verða til þegar það eru stöðug átökum frá ólíkum þjóðfélagshópum. Það sem skýrir refsilögin fyrir fíkniefni er það sama og í samskipta sjónarmiðinu, það er ekkert ólöglegt nema einstaklingur eða hópur segir að þetta er ólöglegt. Til að koma í veg fyrir útbreiðslu á fíkniefnum er sagt að það þyrfti fleiri hagfræði og pólitískari þætti sem mundi minnka glæpi. Það myndi líka minnka dóma sem eru mjög dýrir og grófir með refsingu.',

  refsilögTitil: 'Refsilöggjöfin',
  refsilögText: 'Refsilöggjöfin: Ef manneskja selur eða gefur aðrari manneskju fíkniefni þá getur hún verið í fangelsi í allt að 12 árum.Ef manneskja selur, flytur inn, tekur á móti eða gefur fíkniefni þá er fangelsisdómur allt að 12 árum. Okkur finnst að það er mikið af fíkniefnum í landinu og í öllum heiminum og það þarf einhvereigin að minnka notkun á fíkniefnum. 12 ár í fangelsi fyrir fíkniefni er smá gróft en við skiljum það og teljum það nauðsynlegt. Það sem við mundum breytta væri að ef manneskja fékk sér smá fíkniefni þá kannski aðeins vægari dómur, en ef manneksja flytur inn eða selur fíkniefni þá eru 12 ár góður dómur.',

  refsingTitil: 'Refsing eða betrun:',
  refsingtext: 'Refsing eða betrun: Það sem væri hægt að gera er að setja manneskju í fangelsi eða senda hana á einhverja stofnun til að vinna úr sínum vandamálum. Ef manneskja selur eða flytur inn fíkniefni þá væri best að senda manneskju í fangelsi. Ef manneskja er fíkil og er ekki að selja eða flytja inn fíkniefni þá er stofnun betri staður. Manneskja sem er fíkil fær ekkert úr því að vera inn í fangelsi og er ekkert að vinna í sínum vandamálum. Hún ætti að fara á stofnun og hætti sinni fíkn og laga sín vandamál. Manneskjan væri þá að fara í betrun heldur en refsingu.',
}
export const líkamsárásir = {
  skoðanirTitil: 'Okkar skoðanir',
  skoðanirText: 'Líkamsárásir eru alls staðar í fréttum nú til dags og þar sérstaklega yfir sumarið þar sem fréttir um fólk niður í bæ að ráðast á hvort annað. Þetta er orðið stórt málefni þar sem aukinn hætta er á að verða fyrir líkamsárás sérstaklega í miðbæ Reykjavíkur. Mikil umræða er hjá ungu fólki um líkamsárásir og hegningarlög þeirra sem flestum finnst of lítið. Við erum sammála um það að líkamsárásir eru vandamál og eitthvað sem þarf að taka harðar á.',
  
  samstöðuTitil: 'Samstöðusjónarmiðið',
  samstöðuText: 'Samstöðusjónarmiðið skiptist í tvö sjónarhorn klassíski skólinn og pósitífíski skólinn sem eru með mismunandi kenningar um hvernig refsilög verða til meðal aðra umfangsefni. Klassíski skólinn gefur þá skýringu á refsilagabrot að fólk er frjálst að velja hvort það fremji afbrot eða haldi sér við löginn. Með við líkams árásir þá segir klassíski skólinn að einstaklingar fremja afbrotið að frjálsum vilja. Pósitífíski skólinn vil meina að skýring á afbrotum sé ekki svona skýr en það þurfi að taka inn aðstöðurnar og félagslega þætti til að útskýra hugtakið. Skólinn útskýrir að fólk fæðist hvorki gott eða vont heldur eru það okkar umhverfi og erfðir sem skapa okkur í þann einstakling sem við erum í dag. Í samantekt þá er klassíski skólinn um frjálsan vilja einstaklings en pósitífíski skólinn er meira um sálfræðilegar ástæður.',
  
  samskiptaTitil: 'Samskiptasjónarmiðið',
  samskiptaText: 'Samskiptasjónarmiðið segir fá að afbrotahegðun sé lærð frá jafnöldrum og talar um hvernig afbrotar einstaklingar réttlæta sér brotið með fimm aðferðum. Þetta eru eftirfarandi aðferðir sem eru notaðar til að réttlæta brotið afneitun ábyrgðar, afneitun skaða, afneitun fórnarlambs, fordæming á þeim sem fordæma, hollusta við félagana.  Í samhengi við líkamsárásir þá getur einstaklingur réttlæt brot sitt með afneitun fórnarlambs þar sem afbrotar einstaklingur segir að það sé fórnarlambinu að kenna fyrir brot sitt. ',

  átakaTitil: 'Átakasjónarmiðið',
  átakaText: 'Átakasjónarmiðið talar um að í raun er ekkert afbrot nema hópur skilgreining það sem slíkt. Einnig segir átakasjónarmiðið frá því að í samfélagi eru ólíkir kynættir og menningarhópar sem geta meinað átök á milli hópa. Líkamsárásir eru oft vegna tveggja ólíka hópa sem fara á móti hvor öðrum. Meininginn er sé að mikil togstreita mindist á milli hópa sem endar í afbrotum eins og líkamsárásum. Þetta á mikil við út í heimi þar sem má finna klíkur að berjast við hvor aðra út frá hópum og mismunandi menningar hópum.',

  refsilögTitil: 'Refsilöggjöfin',
  refsilögText: 'Refsing fyrir líkamsárás getur verið allt upp að sex árum í fangelsi og ef brot þykir mjög smávægilegt má beita sektarhegningu. Frá greinn 218 segir að hver sem sakal vera fundinn sekur fyrir líkamsárás skal sæta sektum eða fangelsi upp að einu ári.',

  refsingTitil: 'Refsing eða betrun:',
  refsingtext: 'Aðstæður í tengsli við líkamsárás fer mikið eftir skaðanum sem fórnarlamb verður fyrir og hvort málið er tekið fyrir dóm. Á Íslandi er mikil umræða um líkamsárásir sem eru að gerast niður í miðbæ Reykjavíkur þar sem stóra líkur eru að einn eða báðir aðilar eru ölvaðir. Það er mjög erfitt að dæma í málum en afbrotar einstaklingur þarf alltaf að dvala í fangaklefa í nokkra daga eða viku.',
}
export const netglæpir = {
  skoðanirTitil: 'Okkar skoðanir',
  skoðanirText: 'Allir nota netið og það er allt í kringum okkur. Fólk fer á netið í vonum til að stela upplýsingum, peningum og fleira. Netglæpir gerast mikið í okkar nútíma og margir eru fórnarlömb fyrir þessum glæp. Netið er að stækka og fleiri tækifæri eru fyrir glæpamenn að taka það sem þeir vilja. Netið verður hér eftir tíu ár og netglæpir verða þá hér líka eftir tíu ár.',
  
  samstöðuTitil: 'Samstöðusjónarmiðið',
  samstöðuText: 'Samstöðusjónarmiðið segir að refsilög fyrir netglæpi verða til þegar almenningur segir hvaða viðmið og gildi þarf að fara eftir. Klassíski skólinn segir að manneskjur gera netglæpi og þau stjórna yfir sjálfum sér og ráða hvort þau fylgja lögum. Pósitífíski skólinn segir að manneskja gerir netglæpi ekki út af því hún er góð eða vond heldur er hún líffræðilega gerð til þess að gera það sem hún gerði. klassíski skólinn segir til að koma í veg fyrir útbreiðslu á netglæpum ættu þeir að skoða hækkun í netglæpum og herða refsilög ef þarf. Pósitífíski skólinn segir að það ætti að finna út afhverju manneskjur gera netglæpi og það ætti að reyna að hjálpa með þau vandamál.',
  
  samskiptaTitil: 'Samskiptasjónarmiðið',
  samskiptaText: 'Samskiptasjónarmiðið eru með tvær ástæður um afhverju fólk gerir netglæpi. Kenningar Með áherslu á félagsnám segir að manneskja lærir netglæpi frá sem það er í kringum. Kenningar með áherslu á stimplun segir að netglæpir eru ekki frávik eða afbrot nema hópur eða einstaklingur skilgreinir það sem afbrot. Kenningar með áherslu á félagsnám hefur leið til að koma í veg fyrir útbreiðslu á netglæpum og það væri að draga úr áhrifum hugmynda, minnka hugmynd sem fólk fær um netglæpi og ekk réttláta netglæpi. Kenningar með áherslu á stimplun segir til að koma í veg fyrir útbreiðslu ætti að passa hvernig maður kemur fram við manneskju sem er afbrotamaður og passa að hann gerir ekki brotið aftur.',

  átakaTitil: 'Átakasjónarmiðið',
  átakaText: 'Átakasjónarmiðið segir að refsilög fyrir netglæpi verða til þegar það eru stöðug átökum frá ólíkum þjóðfélagshópum. Það sem skýrir refsilögin fyrir netglæpi er það sama og í samskipta sjónarmiðinu, það er ekkert ólöglegt nema einstaklingur eða hópur segir að þetta er ólöglegt. Til að koma í veg fyrir útbreiðslu á netglæpum er sagt að það þyrfti fleiri hagfræði og pólitískari þætti sem mundi minnka glæpi. Það myndi líka minnka dóma sem eru mjög dýrir og grófir með refsingu.',

  refsilögTitil: 'Refsilöggjöfin:',
  refsilögText: 'Refsilöggjöfin: Það er ekki mikið á netinu um hegningarlög gegn netglæpum. Það sem var nánast netglæpum var að tala við barn á netinu undir aldrinum 15 ára og tala um kynferðislega hluti og fangelsisdómur væri 2 ár. Þjófnaður er tekinn sem netglæpur og getur fengið sex ár í fangelsi fyrir þjófnað. Við teljum að lög fyrir netglæpi eru á gráum stað á Íslandi vegna þess að það er ekki mikið af netglæpum. Okkur finnst þetta samt góðir dómar að vera í sex ár í fangelsi ef þú rænir pening af einhverjum.',

  refsingTitil: 'Refsing eða betrun',
  refsingtext: 'Refsing eða betrun: Ef manneskja er á netinu að stela upplýsingum og peningum finnst okkur að hún ætti að fá bæði refsingu og betrun. Manneskjan hefur gert alvarlegan glæp og þarf að læra frá glæpnum og fara í fangelsi. Okkur finnst að netglæpamenn ættu að fara í fangelsi og líka betrun þar sem þeir geta hætt að afbrota á netinu.',
}
export const könnun = {
  Inngangur: 'Okkur langaði að gera smá könnun þar sem meginn rannsóknarspurning verkefnis var að skoða hvort afbrot munu fjölga á næstu árum í tengsli við netglæpi, líkamsárásir og fíkniefnanotkun. Við vorum með 6 spurningar sem voru mjög líkar í orðalagi þar sem fyrst var spurt hvað þeim finnst vera mikil hætta að verða fyrir ákveðnum glæp. Næsta spurning spurði hvort líklegra væri að verða fyrir glæpum eftir nokkur ár. Svarmöguleikarnir voru eftirfarandi mjög sammála, sammála hvorki né, ósammála, mjög ósammála. Tilgáta okkar var sú ef það væri fleiri sem haka í mjög sammála eða sammála í senni spurningu þá mindi það sýna að fólk trúir að aukning verði á eftirfarandi afbrotum.',
  Niðurstöður: 'Niðurstöður komu frá 146 svarendum þar sem sýnist að fólk trúir að netglæpir muni aukast á næstu árum og voru flest allir mjög sammála og var það stærsti munur á milli. Líkamsárásir voru taldar halda sér við sama en þó nokkrir færðu sig yfir í hvorki né. Fíkniefna neysla heldur sér eins og líkamsárásar spurninginn þar sem flestir halda sér við sama en þó nokkrir sem færa sig yfir í hvorki né.',
}